/* ============================================================
   L1 MATHS — SYNTHÈSE — fiches/java.js
   Rendu + vérification des exercices de la fiche JAVA.
   Tous les exercices sont des QCM à 3 réponses.
   Java n'a jamais fait partie du programme officiel de L1 (ajout
   personnel), mais ce chapitre est désormais construit à partir du
   vrai support de cours "Programmation orientée objet en Java"
   (S2, INU Champollion) : POO généralités, syntaxe, structures
   conditionnelles, boucles, tableaux, classe String, classes
   usuelles (Math/System/Arrays/Random/ArrayList), classes
   personnalisées, héritage/abstraction, interfaces (Comparable),
   gestion des exceptions, AWT et programmation événementielle.
   ============================================================ */

const EXERCISES = [
  {
    id: "ex1", section: "poo",
    statement: "En POO, qu'appelle-t-on un <b>attribut</b> d'un objet ?",
    options: ["Une variable qui caractérise l'objet", "Une fonction qui s'applique à l'objet", "Le nom de la classe"],
    correctIndex: 0,
    explain: "Un attribut est une variable propre à l'objet (par exemple faction, puissance, niveau de vie pour un objet Tank) ; une fonction qui s'applique à l'objet est une méthode.",
  },
  {
    id: "ex2", section: "poo",
    statement: "Que désigne l'<b>instanciation</b> ?",
    options: ["La création d'un nouvel objet à partir d'une classe", "La suppression d'un objet", "La déclaration d'une méthode"],
    correctIndex: 0,
    explain: "Une classe peut être instanciée en autant d'objets que nécessaire ; chaque objet créé est une instance de la classe.",
  },
  {
    id: "ex3", section: "poo",
    statement: "L'<b>encapsulation</b> permet à un objet de...",
    options: ["Masquer son fonctionnement interne et proposer d'y accéder via ses méthodes", "Hériter automatiquement d'une autre classe", "Se dupliquer en plusieurs instances"],
    correctIndex: 0,
    explain: "C'est un des 3 piliers de la POO : le fonctionnement interne de l'objet est masqué, on y accède à travers les méthodes qu'il propose.",
  },
  {
    id: "ex4", section: "poo",
    statement: "L'<b>héritage</b> permet à une classe fille de...",
    options: ["Hériter des attributs et méthodes de sa classe mère, tout en pouvant les redéfinir", "Devenir automatiquement une interface", "Empêcher toute instanciation"],
    correctIndex: 0,
    explain: "Les classes filles héritent (ou dérivent) de leur classe mère, et peuvent surcharger certains comportements hérités.",
  },
  {
    id: "ex5", section: "poo",
    statement: "Le <b>polymorphisme</b> permet à une méthode de...",
    options: ["Définir des comportements différents selon l'objet ou les paramètres avec lesquels elle est appelée", "Ne jamais changer de comportement", "Devenir un attribut"],
    correctIndex: 0,
    explain: "Exemple du cours : un fantassin et un grenadier n'« attaquent » pas de la même manière — même nom de méthode, comportements différents selon l'objet appelant.",
  },
  {
    id: "ex6", section: "poo",
    statement: "<code>public static String FAMILLY = \"ITEMS\";</code> déclaré directement dans une classe : de quoi s'agit-il ?",
    options: ["Un attribut de classe (static)", "Un attribut d'instance", "Une méthode de classe"],
    correctIndex: 0,
    explain: "Le mot-clé static rend cet attribut commun à toutes les instances de la classe, plutôt que propre à chaque objet créé.",
  },
  {
    id: "ex7", section: "poo",
    statement: "<code>public KeyWord(String name, int capacity){<br>&nbsp;&nbsp;this(name, capacity, 0);<br>}</code><br>Sachant qu'un autre constructeur <code>KeyWord(String, int, int)</code> existe déjà, que représente ce deuxième constructeur ?",
    options: ["Une surcharge de méthode (ici, de constructeur)", "Un héritage", "Une exception"],
    correctIndex: 0,
    explain: "Deux constructeurs de même nom mais de paramètres différents : c'est une surcharge. Ici le second délègue au premier via this(...).",
  },
  {
    id: "ex8", section: "syntaxe-java",
    statement: "En Java, comment sépare-t-on deux instructions dans un même bloc ?",
    options: ["Par un point-virgule ;", "Par un retour à la ligne, comme en Python", "Par une virgule"],
    correctIndex: 0,
    explain: "Le point-virgule est le caractère de la « séquence algorithmique » en Java ; en Python, c'est l'indentation/le retour à la ligne qui joue ce rôle.",
  },
  {
    id: "ex9", section: "syntaxe-java",
    statement: "Comment un bloc de code est-il délimité en Java ?",
    options: ["Par des accolades { }", "Par l'indentation", "Par des deux-points :"],
    correctIndex: 0,
    explain: "Contrairement à Python où l'indentation délimite les blocs, Java utilise des accolades explicites.",
  },
  {
    id: "ex10", section: "syntaxe-java",
    statement: "Laquelle de ces déclarations de variable est valide en Java ?",
    options: ["<code>int x = 42;</code>", "<code>x = 42;</code>", "<code>var x := 42;</code>"],
    correctIndex: 0,
    explain: "Les variables Java sont déclarées précédées de leur type (ici int) : on ne peut pas se contenter d'une simple affectation comme en Python.",
  },
  {
    id: "ex11", section: "conditions-java",
    statement: "Quels mots-clés servent à écrire une structure conditionnelle en Java ?",
    options: ["<code>if</code> et <code>else</code>", "<code>when</code> et <code>otherwise</code>", "<code>cond</code> et <code>alt</code>"],
    correctIndex: 0,
    explain: "Une structure conditionnelle exécute un bloc si une condition (valeur booléenne) est remplie, avec if / else, éventuellement imbriqués.",
  },
  {
    id: "ex12", section: "conditions-java",
    statement: "Exercice du cours : calculer m, le multiple de 5 le plus proche de n (n≥0). Si n=43, que vaut m ?",
    options: ["<code>45</code>", "<code>40</code>", "<code>43</code>"],
    correctIndex: 0,
    explain: "43 est à 3 de 40 et à 2 de 45 : le multiple de 5 le plus proche est donc 45 (comme donné en exemple dans l'énoncé du cours).",
  },
  {
    id: "ex13", section: "conditions-java",
    statement: "Même exercice : si n=45, que vaut m ?",
    options: ["<code>45</code>", "<code>40</code>", "<code>50</code>"],
    correctIndex: 0,
    explain: "45 est déjà un multiple de 5 : m=45.",
  },
  {
    id: "ex14", section: "boucles-java",
    statement: "Quelle boucle utilise-t-on quand le nombre d'itérations est connu à l'avance ?",
    options: ["<code>for</code>", "<code>while</code>", "Les deux sont strictement équivalentes en Java"],
    correctIndex: 0,
    explain: "for permet d'exécuter un bloc un nombre défini de fois (une variable est incrémentée/décrémentée, la condition d'arrêt apparaît explicitement) ; while répète tant qu'une condition reste vraie, sans nombre d'itérations connu à l'avance.",
  },
  {
    id: "ex15", section: "boucles-java",
    statement: "Suite du cours : n évolue en n/2 si n est pair, et 3n+1 si n est impair, jusqu'à n=1 (suite de Syracuse). En partant de n=6, quelle est la 2ᵉ valeur obtenue ?",
    options: ["<code>3</code>", "<code>19</code>", "<code>1</code>"],
    correctIndex: 0,
    explain: "6 est pair → 6/2 = 3. (Puis 3 est impair → 3×3+1 = 10, etc.)",
  },
  {
    id: "ex16", section: "boucles-java",
    statement: "<code>for (int i = 0; i &lt; 3; i++) { System.out.println(i); }</code><br>Combien de fois println s'exécute-t-il ?",
    options: ["3 fois", "2 fois", "4 fois"],
    correctIndex: 0,
    explain: "i vaut successivement 0, 1, 2 (3 tours), puis la condition i<3 devient fausse pour i=3 : la boucle s'arrête.",
  },
  {
    id: "ex17", section: "tableaux-java",
    statement: "Dans un tableau Java, quel est l'indice du premier élément ?",
    options: ["<code>0</code>", "<code>1</code>", "Cela dépend du type du tableau"],
    correctIndex: 0,
    explain: "Comme dans la plupart des langages, les indices d'un tableau Java commencent toujours à 0.",
  },
  {
    id: "ex18", section: "tableaux-java",
    statement: "Après <code>int[] t = {10, 20, 30};</code>, comment obtenir le nombre d'éléments de t ?",
    options: ["<code>t.length</code>", "<code>t.length()</code>", "<code>len(t)</code>"],
    correctIndex: 0,
    explain: "length est un attribut du tableau (pas une méthode) : pas de parenthèses, contrairement à ce qu'on pourrait attendre.",
  },
  {
    id: "ex19", section: "tableaux-java",
    statement: "Toujours avec <code>int[] t = {10, 20, 30};</code>, que se passe-t-il si on accède à <code>t[3]</code> ?",
    options: ["Une exception ArrayIndexOutOfBoundsException", "Cela renvoie 0 par défaut", "Cela renvoie null"],
    correctIndex: 0,
    explain: "Les indices valides vont de 0 à t.length-1 (soit 0 à 2 ici) ; dépasser cette borne lève une exception, contrairement à Python qui lèverait un IndexError similaire mais avec un nom différent.",
  },
  {
    id: "ex20", section: "tableaux-java",
    statement: "Quand un tableau Java est créé avec <code>new</code> sans valeurs initiales fournies, comment ses cases sont-elles initialisées par défaut ?",
    options: ["Selon le type : false pour les booléens, 0 pour les entiers, null pour les objets", "Toutes les cases restent indéfinies (erreur si on y accède)", "Toutes les cases valent -1"],
    correctIndex: 0,
    explain: "Java initialise systématiquement chaque case à une valeur par défaut dépendant du type, contrairement à des langages qui laissent la mémoire non initialisée.",
  },
  {
    id: "ex21", section: "chaines-java",
    statement: "En Java, la classe <code>String</code> hérite de quelle classe ?",
    options: ["<code>Object</code>", "<code>Array</code>", "Aucune, String est une classe racine"],
    correctIndex: 0,
    explain: "Object est la racine de la hiérarchie de toutes les classes Java ; String en hérite comme toute autre classe.",
  },
  {
    id: "ex22", section: "chaines-java",
    statement: "Que se passe-t-il si on tente d'accéder à un attribut ou une méthode d'un objet Java déclaré mais non instancié (donc <code>null</code>) ?",
    options: ["Une exception NullPointerException est levée", "Java retourne une valeur par défaut", "Le programme continue silencieusement"],
    correctIndex: 0,
    explain: "Un objet nul n'occupe aucune place en mémoire ; toute tentative d'accès à ses attributs/méthodes lève une NullPointerException.",
  },
  {
    id: "ex23", section: "chaines-java",
    statement: "Quelle méthode de la classe String permet d'obtenir le caractère à l'indice i ?",
    options: ["<code>charAt(i)</code>", "<code>getChar(i)</code>", "<code>s[i]</code>"],
    correctIndex: 0,
    explain: "Contrairement à Python où s[i] fonctionne directement, Java utilise la méthode charAt(i) sur un objet String.",
  },
  {
    id: "ex24", section: "classes-usuelles-java",
    statement: "La classe <code>Random</code> (utilisée pour l'aléatoire en Java) appartient à quel paquetage ?",
    options: ["<code>java.util</code>", "<code>java.lang</code>", "<code>java.random</code>"],
    correctIndex: 0,
    explain: "Random doit être importée du paquetage java.util avant de pouvoir être utilisée.",
  },
  {
    id: "ex25", section: "classes-usuelles-java",
    statement: "À quoi sert de fixer explicitement une graine (seed) au constructeur de Random ?",
    options: ["Obtenir la même séquence de nombres à chaque exécution (utile pour les tests)", "Rendre les nombres générés vraiment aléatoires", "Accélérer la génération de nombres"],
    correctIndex: 0,
    explain: "Sans graine fixée, la séquence change à chaque exécution ; avec une graine fixe, le programme redonne toujours la même séquence, ce qui facilite le débogage et les tests.",
  },
  {
    id: "ex26", section: "classes-usuelles-java",
    statement: "Quelle est la différence essentielle entre un tableau Java et un <code>ArrayList</code> ?",
    options: ["ArrayList est une liste extensible, contrairement au tableau dont la taille est fixe", "ArrayList ne peut contenir que des entiers", "Un tableau est plus lent qu'un ArrayList"],
    correctIndex: 0,
    explain: "ArrayList (paquetage java.util) est une classe paramétrée (List&lt;String&gt;, List&lt;Integer&gt;, etc.) dont la taille peut évoluer, contrairement à un tableau classique.",
  },
  {
    id: "ex27", section: "classes-usuelles-java",
    statement: "Pourquoi ne peut-on pas écrire <code>new Math()</code> en Java ?",
    options: ["Math ne peut pas être instanciée : elle ne propose que des constantes et méthodes de classe (Math.PI, Math.pow()...)", "Math n'existe pas en Java", "Il faut toujours écrire Math.new()"],
    correctIndex: 0,
    explain: "Math, System et Arrays sont des classes qui ne peuvent pas être instanciées : leur constructeur est invisible, on utilise directement leurs méthodes de classe.",
  },
  {
    id: "ex28", section: "classes-usuelles-java",
    statement: "Quelle méthode de la classe Arrays permet d'obtenir une représentation textuelle lisible d'un tableau ?",
    options: ["<code>Arrays.toString(t)</code>", "<code>t.print()</code>", "<code>String(t)</code>"],
    correctIndex: 0,
    explain: "La classe Arrays propose des méthodes de classe facilitant la gestion des tableaux : toString(), sort(), equals(), fill(), etc.",
  },
  {
    id: "ex29", section: "classes-perso-java",
    statement: "Par convention, comment commence le nom d'une classe personnalisée en Java ?",
    options: ["Par une majuscule", "Par une minuscule", "Par un underscore"],
    correctIndex: 0,
    explain: "Convention Java : les noms de classe commencent par une majuscule (les attributs et méthodes, eux, commencent en minuscule).",
  },
  {
    id: "ex30", section: "classes-perso-java",
    statement: "Dans une méthode d'une classe, à quoi sert le mot-clé <code>this</code> ?",
    options: ["Il désigne l'instance sur laquelle la méthode est appelée", "Il désigne la classe mère", "Il crée une nouvelle instance"],
    correctIndex: 0,
    explain: "this permet à une méthode de faire référence à l'objet courant, par exemple pour distinguer un attribut d'un paramètre de même nom.",
  },
  {
    id: "ex31", section: "classes-perso-java",
    statement: "Quelle particularité a le constructeur d'une classe Java ?",
    options: ["Il porte le nom de la classe et n'a pas de type de retour", "Il doit obligatoirement s'appeler init()", "Il ne peut prendre aucun paramètre"],
    correctIndex: 0,
    explain: "Le constructeur permet de « paramétrer » la nouvelle instance créée ; il partage le nom de la classe et n'a pas de type de retour (même pas void).",
  },
  {
    id: "ex32", section: "classes-perso-java",
    statement: "À quoi sert de redéfinir la méthode <code>toString()</code> dans une classe personnalisée ?",
    options: ["Représenter l'instance courante sous forme de chaîne de caractères (pour l'affichage)", "Comparer deux instances entre elles", "Détruire l'instance"],
    correctIndex: 0,
    explain: "toString() (comme equals()) redéfinit une méthode héritée de la classe Object ; elle sert à obtenir une représentation textuelle de l'objet, utile pour print/console.",
  },
  {
    id: "ex33", section: "heritage-java",
    statement: "Quel mot-clé permet à une classe Java de dériver (hériter) d'une autre ?",
    options: ["<code>extends</code>", "<code>implements</code>", "<code>inherits</code>"],
    correctIndex: 0,
    explain: "On dérive une sous-classe au moment de sa déclaration avec extends ; les attributs et méthodes non privés de la classe mère sont alors automatiquement disponibles.",
  },
  {
    id: "ex34", section: "heritage-java",
    statement: "Dans une méthode redéfinie par une classe fille, quel mot-clé permet d'appeler la version de la classe mère (superclasse) ?",
    options: ["<code>super</code>", "<code>this</code>", "<code>parent</code>"],
    correctIndex: 0,
    explain: "Les méthodes redéfinies peuvent faire appel aux méthodes de la superclasse grâce au mot-clé super.",
  },
  {
    id: "ex35", section: "heritage-java",
    statement: "Que signifie rendre une méthode <code>abstract</code> dans une classe ?",
    options: ["Elle n'a pas de code dans cette classe ; les classes filles doivent l'implémenter", "Elle ne peut jamais être appelée", "Elle devient automatiquement privée"],
    correctIndex: 0,
    explain: "Une classe contenant au moins une méthode abstraite devient elle-même une classe abstraite (mot-clé abstract), et ne peut pas être instanciée directement.",
  },
  {
    id: "ex36", section: "heritage-java",
    statement: "Peut-on écrire <code>new Animal()</code> si <code>Animal</code> est déclarée <code>abstract class Animal</code> ?",
    options: ["Non, une classe abstraite ne peut jamais être instanciée", "Oui, sans restriction", "Oui, mais seulement dans le programme principal"],
    correctIndex: 0,
    explain: "Une classe abstraite ne peut pas être instanciée ; seules ses classes filles concrètes (qui implémentent ses méthodes abstraites) peuvent l'être.",
  },
  {
    id: "ex37", section: "interfaces-java",
    statement: "Que peut contenir une <b>interface</b> Java ?",
    options: ["Uniquement des signatures de méthodes (méthodes abstraites), sans code", "Des attributs et du code complet comme une classe normale", "Uniquement des constantes numériques"],
    correctIndex: 0,
    explain: "Une interface déclare des méthodes (visibilité, type, nom, paramètres) mais ne fournit pas leur code ; elle ne peut donc pas être instanciée, seulement implémentée.",
  },
  {
    id: "ex38", section: "interfaces-java",
    statement: "Quel mot-clé une classe utilise-t-elle pour indiquer qu'elle implémente une interface ?",
    options: ["<code>implements</code>", "<code>extends</code>", "<code>uses</code>"],
    correctIndex: 0,
    explain: "Une classe qui implémente une interface le déclare en en-tête avec implements, puis doit fournir le code de toutes les méthodes de l'interface.",
  },
  {
    id: "ex39", section: "interfaces-java",
    statement: "Que retourne la méthode <code>compareTo</code> de l'interface <code>Comparable&lt;T&gt;</code> ?",
    options: ["Un entier signé représentant la différence entre l'objet courant et l'objet comparé", "Toujours un booléen", "Toujours 0 ou 1"],
    correctIndex: 0,
    explain: "La comparaison retourne un entier correspondant à la « différence » entre this et l'objet comparé ; sa valeur absolue caractérise une distance.",
  },
  {
    id: "ex40", section: "interfaces-java",
    statement: "Pourquoi une classe a-t-elle intérêt à implémenter <code>Comparable</code> ?",
    options: ["Pour être compatible avec des méthodes comme Collections.sort, qui exigent des éléments comparables", "Parce que c'est obligatoire pour toute classe Java", "Pour pouvoir être affichée avec System.out.println"],
    correctIndex: 0,
    explain: "Par exemple, Collections.sort attend en paramètre une collection d'éléments qui implémentent Comparable : implémenter cette interface rend la classe compatible avec ce contrat.",
  },
  {
    id: "ex41", section: "exceptions-java",
    statement: "Qu'est-ce qu'une <b>exception</b> en Java ?",
    options: ["Un objet qui représente une erreur survenue pendant l'exécution, levé au lieu de faire planter le programme", "Un simple message affiché dans la console qui n'arrête jamais le programme", "Un type de boucle qui s'arrête automatiquement en cas d'erreur"],
    correctIndex: 0,
    explain: "Au lieu de crasher directement, le programme lève (déclenche) un objet exception, qui peut ensuite être capturé et traité par un gestionnaire.",
  },
  {
    id: "ex42", section: "exceptions-java",
    statement: "Que fait un bloc <code>try</code> / <code>catch</code> ?",
    options: ["Il exécute le code du try, et si une exception y est levée, elle est interceptée et traitée dans le catch", "Il empêche définitivement toute exception de se produire dans le programme", "Il relance automatiquement le programme depuis le début en cas d'erreur"],
    correctIndex: 0,
    explain: "try délimite le code à risque ; si une exception y survient, elle est capturée par le catch correspondant, ce qui évite l'arrêt brutal du programme.",
  },
  {
    id: "ex43", section: "exceptions-java",
    statement: "Quelle est la différence entre <code>throw</code> et <code>throws</code> ?",
    options: ["throw déclenche effectivement une exception dans le code ; throws, dans la signature d'une méthode, annonce qu'elle est susceptible d'en lever une", "Ce sont deux synonymes strictement interchangeables en Java", "throw sert aux erreurs graves, throws aux erreurs mineures"],
    correctIndex: 0,
    explain: "throw lève concrètement un objet exception à un endroit précis du code ; throws est une déclaration dans l'en-tête d'une méthode qui prévient qu'elle peut propager une exception.",
  },
  {
    id: "ex44", section: "exceptions-java",
    statement: "Une <b>exception personnalisée</b> doit dériver de quelle classe ?",
    options: ["<code>java.lang.Exception</code> (directement ou indirectement)", "<code>java.lang.Object</code> uniquement, comme n'importe quelle classe", "Aucune : une exception personnalisée est une interface"],
    correctIndex: 0,
    explain: "Toutes les exceptions Java dérivent de java.lang.Exception ; une exception personnalisée en hérite pour bénéficier du même mécanisme de levée/capture.",
  },
  {
    id: "ex45", section: "exceptions-java",
    statement: "Si aucune méthode de la pile d'appel ne capture une exception levée, que se passe-t-il ?",
    options: ["Elle continue à se propager jusqu'à la méthode main, et le programme s'arrête en affichant la stack trace", "Elle est ignorée silencieusement et le programme continue normalement", "Elle est automatiquement transformée en simple avertissement"],
    correctIndex: 0,
    explain: "Sans handler pour l'intercepter, l'exception remonte (se propage) toute la pile d'appel jusqu'à main, provoquant l'arrêt du programme.",
  },
  {
    id: "ex46", section: "exceptions-java",
    statement: "Que représente la <b>stack trace</b> d'une exception ?",
    options: ["La pile des méthodes appelées, depuis main jusqu'à celle où l'exception a été levée, utile pour déboguer", "La liste des variables locales au moment du crash", "Le nombre de fois où l'exception a été levée pendant l'exécution"],
    correctIndex: 0,
    explain: "Elle retrace le chemin d'appel des méthodes jusqu'au point où l'exception a été levée, ce qui aide à localiser l'origine du problème.",
  },
  {
    id: "ex47", section: "awt-java",
    statement: "Quelle classe AWT sert de zone rectangulaire dans laquelle on peut dessiner ?",
    options: ["<code>Canvas</code>", "<code>Frame</code>", "<code>Graphics</code>"],
    correctIndex: 0,
    explain: "Le Canvas est la zone de dessin ; on la personnalise en dérivant une classe qui hérite de Canvas et redéfinit sa méthode paint().",
  },
  {
    id: "ex48", section: "awt-java",
    statement: "Quelle méthode faut-il redéfinir (surcharger) pour personnaliser l'affichage d'un Canvas ?",
    options: ["<code>paint()</code>, qui reçoit un objet Graphics en paramètre", "<code>main()</code>", "<code>toString()</code>"],
    correctIndex: 0,
    explain: "paint(Graphics g) est appelée pour dessiner ; les méthodes de l'objet Graphics passé en paramètre permettent de tracer formes, images, texte, etc.",
  },
  {
    id: "ex49", section: "awt-java",
    statement: "Pour associer un écouteur à un composant avec <code>X.addYListener(Z)</code>, que doit-on vérifier ?",
    options: ["X est un composant qui émet des événements de type YEvent, et Z implémente l'interface YListener", "X et Z doivent obligatoirement être la même instance", "Y est le nom d'une méthode qu'il faut définir directement dans X"],
    correctIndex: 0,
    explain: "Le composant (X) est apparié à un écouteur (Z) qui implémente l'interface adéquate (YListener) pour réagir aux événements que X émet.",
  },
  {
    id: "ex50", section: "awt-java",
    statement: "Quelle est la différence entre <code>keyPressed</code> et <code>keyTyped</code> dans <code>KeyListener</code> ?",
    options: ["keyPressed réagit à l'appui physique sur une touche (y compris flèches, touches spéciales), keyTyped réagit uniquement aux caractères produits", "Ce sont deux noms différents pour exactement le même événement", "keyTyped se déclenche systématiquement avant keyPressed"],
    correctIndex: 0,
    explain: "keyPressed capture toute touche physique enfoncée (utile par exemple pour les flèches directionnelles), tandis que keyTyped ne réagit qu'aux caractères réellement saisis.",
  },
  {
    id: "ex51", section: "awt-java",
    statement: "Une classe qui implémente une interface d'écouteur (ex. <code>MouseListener</code>) doit :",
    options: ["Fournir une implémentation pour chacune des méthodes de l'interface, même vide", "Fournir uniquement le code de la méthode qui l'intéresse", "Redéfinir uniquement les méthodes statiques de l'interface"],
    correctIndex: 0,
    explain: "Implémenter une interface impose de fournir le code de toutes ses méthodes, quitte à laisser certains corps vides si l'événement correspondant n'est pas utile ici.",
  },
  {
    id: "ex52", section: "awt-java",
    statement: "Quelle méthode d'un Canvas permet de le redessiner après une modification (ex. une forme ajoutée) ?",
    options: ["<code>repaint()</code>", "<code>refresh()</code>", "<code>update()</code> uniquement, sans jamais passer par repaint()"],
    correctIndex: 0,
    explain: "repaint() planifie un nouvel appel à paint() pour que le Canvas reflète les changements, par exemple une nouvelle forme à afficher.",
  },
];

const SECTIONS = [
  {
    id: "poo", title: "§1 — PROGRAMMATION ORIENTÉE OBJET : CONCEPTS",
    cours: "Un <span class=\"math\">objet</span> est une brique logicielle qui possède une structure (ses <span class=\"math\">attributs</span>, des variables) et un comportement (ses <span class=\"math\">méthodes</span>, des fonctions qui s'appliquent à l'objet)<br>Les objets sont issus de <span class=\"math\">classes</span>, réutilisables et personnalisables ; l'<span class=\"math\">instanciation</span> désigne la création d'un objet à partir d'une classe<br>Les 3 piliers de la POO : <span class=\"math\">encapsulation</span> (masquer le fonctionnement interne, y accéder via les méthodes), <span class=\"math\">héritage</span> (une classe fille hérite/dérive d'une classe mère), <span class=\"math\">polymorphisme</span> (une méthode se comporte différemment selon l'objet ou les paramètres)<br>Un attribut <code>static</code> (attribut de classe) est commun à toutes les instances, contrairement à un attribut d'instance propre à chaque objet<br>Deux méthodes (ou constructeurs) de même nom mais de paramètres différents constituent une <span class=\"math\">surcharge</span>",
  },
  {
    id: "syntaxe-java", title: "§2 — PREMIERS PAS AVEC JAVA",
    cours: "Chaque instruction se termine par un point-virgule <code>;</code> (en Python, on retourne simplement à la ligne)<br>Un bloc de code est délimité par des accolades <code>{ }</code> (en Python, c'est l'indentation qui joue ce rôle)<br>Commentaires : <code>/* bloc */</code> ou <code>// une ligne</code><br>Les variables sont déclarées précédées de leur <span class=\"math\">type</span> : <code>int x = 42;</code>, jamais <code>x = 42;</code> seul<br>Tout programme Java nécessite une méthode <code>main</code>, point d'entrée de l'exécution",
  },
  {
    id: "conditions-java", title: "§3 — STRUCTURES CONDITIONNELLES",
    cours: "Les structures conditionnelles <code>if</code> / <code>else</code> exécutent un bloc lorsqu'une condition (valeur booléenne) est remplie<br>Elles peuvent être imbriquées les unes dans les autres<br>Opérateurs de comparaison : <code>==</code>, <code>!=</code>, <code>&gt;</code>, <code>&gt;=</code>, <code>&lt;</code>, <code>&lt;=</code> ; opérateurs booléens : <code>&amp;&amp;</code>, <code>||</code>, <code>!</code>",
  },
  {
    id: "boucles-java", title: "§4 — BOUCLES",
    cours: "<code>for</code> : exécute un bloc un nombre défini de fois (variable incrémentée/décrémentée, condition d'arrêt explicite)<br><code>while</code> : répète tant qu'une condition reste remplie, sans nombre d'itérations connu à l'avance",
  },
  {
    id: "tableaux-java", title: "§5 — LES TABLEAUX",
    cours: "Un tableau est une collection séquentielle de valeurs du même type, accessible par indice (toujours à partir de <code>0</code>)<br>Le mot-clé <code>new</code> réserve l'espace mémoire ; sans valeurs fournies, les cases sont initialisées par défaut selon le type (<code>false</code>, <code>0</code>, <code>null</code>...)<br>L'attribut <code>length</code> (sans parenthèses !) donne la taille du tableau<br>Un accès hors bornes (indice ≥ length) lève une <code>ArrayIndexOutOfBoundsException</code><br>Parcours : boucle <code>for</code> classique sur les indices, ou boucle <code>foreach</code> plus concise",
  },
  {
    id: "chaines-java", title: "§6 — LA CLASSE STRING",
    cours: "<code>String</code> est une classe comme une autre, qui hérite de <code>Object</code> (racine de toutes les classes Java)<br>Un objet déclaré mais non instancié vaut <code>null</code> ; toute tentative d'accès à ses attributs/méthodes lève une <code>NullPointerException</code><br>Méthodes courantes : <code>length()</code> (nombre de caractères), <code>charAt(i)</code> (caractère à l'indice i)<br>Java optimise l'usage des chaînes via un « réservoir partagé » (string pool) pour les chaînes créées sans <code>new</code>",
  },
  {
    id: "classes-usuelles-java", title: "§7 — CLASSES USUELLES",
    cours: "<code>Random</code> (paquetage <code>java.util</code>) gère l'aléatoire ; fixer une graine (seed) au constructeur rend la séquence reproductible, utile pour les tests<br><code>ArrayList</code> (paquetage <code>java.util</code>) est une liste extensible et paramétrée (<code>List&lt;String&gt;</code>, <code>List&lt;Integer&gt;</code>...), contrairement au tableau classique à taille fixe<br><code>Math</code>, <code>System</code>, <code>Arrays</code> ne peuvent pas être instanciées : elles ne proposent que des constantes et méthodes de classe (<code>Math.PI</code>, <code>Math.pow()</code>, <code>System.out.println()</code>, <code>Arrays.toString()</code>, <code>Arrays.sort()</code>...)",
  },
  {
    id: "classes-perso-java", title: "§8 — CRÉER SES CLASSES PERSONNALISÉES",
    cours: "Une classe se déclare avec le mot-clé <code>class</code> ; par convention son nom commence par une majuscule, ses attributs sont déclarés avant ses méthodes<br>La visibilité (<code>public</code>, <code>protected</code>, <code>private</code>) détermine si un attribut/une méthode est accessible depuis l'extérieur de la classe<br>Le <span class=\"math\">constructeur</span> porte le nom de la classe, n'a pas de type de retour, et sert à paramétrer la nouvelle instance<br><code>this</code> désigne, dans une méthode, l'instance sur laquelle elle est appelée<br>Redéfinir <code>toString()</code> permet de représenter l'objet sous forme de texte ; redéfinir <code>equals()</code> permet de comparer deux instances — ce sont des redéfinitions de méthodes héritées de <code>Object</code>",
  },
  {
    id: "heritage-java", title: "§9 — HÉRITAGE ET ABSTRACTION",
    cours: "Le mot-clé <code>extends</code> fait dériver une classe fille d'une classe mère (superclasse) ; les attributs/méthodes non privés de la mère deviennent disponibles pour la fille<br>La classe fille peut ajouter des attributs/méthodes ou redéfinir des méthodes héritées ; <code>super</code> permet d'appeler la version de la méthode dans la classe mère<br>Une méthode <code>abstract</code> n'a pas de code dans la classe qui la déclare ; une classe contenant au moins une méthode abstraite devient elle-même <code>abstract</code> et ne peut pas être instanciée directement — seules ses classes filles concrètes (qui implémentent ses méthodes abstraites) le peuvent",
  },
  {
    id: "interfaces-java", title: "§10 — LES INTERFACES (COMPARABLE)",
    cours: "Une <span class=\"math\">interface</span> ne contient que des signatures de méthodes (méthodes abstraites), sans code ; elle ne peut pas être instanciée, seulement implémentée (mot-clé <code>implements</code>) par une ou plusieurs classes<br>L'interface propose un « contrat » plutôt qu'un service<br><code>Comparable&lt;T&gt;</code> propose une seule méthode <code>compareTo</code>, qui retourne un entier signé représentant la « différence » entre l'objet courant et l'objet comparé<br>Implémenter Comparable rend une classe compatible avec des méthodes comme <code>Collections.sort</code>, qui exigent des éléments comparables entre eux",
  },
  {
    id: "exceptions-java", title: "§11 — GESTION DES EXCEPTIONS",
    cours: "Une <span class=\"math\">exception</span> est un objet représentant une erreur survenue pendant l'exécution ; au lieu de faire planter le programme, elle est levée puis peut être capturée et traitée<br>Un bloc <code>try</code> délimite le code à risque ; si une exception y est levée, elle est interceptée par le <code>catch</code> correspondant<br><code>throw</code> lève effectivement une exception dans le code ; <code>throws</code>, dans la signature d'une méthode, annonce qu'elle est susceptible d'en lever une<br>Une exception personnalisée dérive de <code>java.lang.Exception</code><br>Sans handler pour la capturer, une exception se propage le long de la pile d'appel jusqu'à <code>main</code>, provoquant l'arrêt du programme (la <span class=\"math\">stack trace</span> retrace ce chemin d'appel)",
  },
  {
    id: "awt-java", title: "§12 — AWT ET LA PROGRAMMATION ÉVÉNEMENTIELLE",
    cours: "AWT (<span class=\"math\">Abstract Window Toolkit</span>) est le premier environnement graphique de Java ; le <code>Canvas</code> est sa zone de dessin, personnalisée en redéfinissant la méthode <code>paint(Graphics g)</code><br>Une application graphique attend des <span class=\"math\">événements</span> (clic, touche, déplacement...) plutôt que de dérouler un algorithme linéaire<br>Un <span class=\"math\">écouteur</span> (listener) est une interface Java ; une classe qui l'implémente doit fournir le code de toutes ses méthodes, même vides<br>Le montage <code>X.addYListener(Z)</code> suppose que X émette des événements de type YEvent et que Z implémente l'interface YListener<br><code>keyPressed</code> réagit à toute touche physique enfoncée, <code>keyTyped</code> uniquement aux caractères produits<br><code>repaint()</code> planifie un nouvel appel à <code>paint()</code> pour refléter un changement",
  },
];

initFiche({ STATE_KEY: 'l1maths_java_state', CHAPTER_ID: 'java', EXERCISES, SECTIONS });
