/* ============================================================
   L1 MATHS — SYNTHÈSE — changelog.js
   Historique des versions du site (page changelog.html).
   Liste manuelle, à compléter à chaque nouvelle valeur de
   SITE_VERSION dans menu.js. Dates au format JJ/MM/AAAA.
   ============================================================ */

const VERSIONS = [
  { v: 138, date: "18/08/2026", desc: "<ul><li>Libellés « PROGRESSION TOTALE » / « PROGRESSION HEBDOMADAIRE » sur les deux barres du haut</li><li>Tooltip de la barre totale précise qu'elle ne se remet à zéro qu'en cas de réinitialisation complète</li></ul>" },
  { v: 137, date: "18/08/2026", desc: "<ul><li>Bulle de l'oiseau remise au-dessus, avec l'espace réservé qu'il faut</li><li>L'oiseau ne disparaît plus quand on appuie dessus</li></ul>" },
  { v: 136, date: "18/08/2026", desc: "<ul><li>Bulle de l'oiseau redirigée sous lui (chevauchait la dernière carte de chapitre)</li><li>Bouton « réinitialiser ma semaine » sur la page progression, sans toucher au reste</li></ul>" },
  { v: 135, date: "18/08/2026", desc: "<ul><li>Scène de combat remontée juste sous les deux barres du haut</li><li>Le dragon garde sa taille maximale tous les jours, seule sa position avance</li></ul>" },
  { v: 134, date: "18/08/2026", desc: "<ul><li>Scène de combat simplifiée : château/grotte/lune retirés, dragon et chevalier sur une seule ligne</li><li>L'oiseau isolé tout en bas de la page</li></ul>" },
  { v: 133, date: "18/08/2026", desc: "Objectif hebdomadaire affiché en repère sur la barre, plus en texte" },
  { v: 132, date: "18/08/2026", desc: "Nouvelle barre hebdomadaire sous la barre totale, en haut de l'accueil" },
  { v: 131, date: "12/08/2026", desc: "<ul><li>L'oiseau se cache derrière le chevalier dès mercredi (au lieu de vendredi)</li><li>Lune légèrement penchée</li><li>Tirer la phrase de sagesse tout en bas en charge une nouvelle à chaque fois</li></ul>" },
  { v: 130, date: "12/08/2026", desc: "<ul><li>Barrière de campagne retirée de la scène de combat</li><li>Contour du dragon reconstruit en profondeur (toujours invisible sur iPhone malgré le correctif précédent)</li></ul>" },
  { v: 129, date: "12/08/2026", desc: "<ul><li>Contour du dragon invisible sur iPhone réel : corrigé</li><li>Phrase de sagesse et ligne de séparation cachées, révélées en tirant tout en bas de la page</li></ul>" },
  { v: 128, date: "11/08/2026", desc: "<ul><li>Curseurs clignotants restants retirés (accueil et 5 autres pages)</li><li>Dragon en couleurs inversées, contour blanc</li><li>Clignement de l'oiseau parfois long (œil fermé 1s)</li><li>Historique : « ACTUELLE » et cadre épais retirés</li><li>Anciens commentaires de version simplifiés</li></ul>" },
  { v: 127, date: "11/08/2026", desc: "<ul><li>Dragon du samedi bien plus grand (poitrine à hauteur de tête)</li><li>L'oiseau se cache derrière le chevalier en fin de semaine</li></ul>" },
  { v: 126, date: "11/08/2026", desc: "<ul><li>Curseur clignotant retiré en fin de fiche</li><li>Petit monstre errant retiré</li><li>Dragon affiché devant la barrière</li></ul>" },
  { v: 125, date: "11/08/2026", desc: "<ul><li>Espaces vides réduits autour du château et du combat</li><li>Pied de page : ne passe plus sous les boutons du bas</li></ul>" },
  { v: 124, date: "11/08/2026", desc: "<ul><li>Rond de réponse aligné sur la 1re ligne du texte</li><li>Formules qui débordaient dans les QCM : corrigé</li><li>Point orphelin retiré après certaines formules</li><li>Score des fiches simplifié (retrait de « complétés »)</li><li>Export/import : la pile de crânes est incluse</li><li>Rythme du cœur du menu varie avec le taux de bonnes réponses</li></ul>" },
  { v: 123, date: "11/08/2026", desc: "<ul><li>Cartes de chapitre : cadre affiné, moins imposant</li><li>Bouton retour-en-haut et badge de version : réactifs tout en bas sur iPhone récent</li></ul>" },
  { v: 122, date: "11/08/2026", desc: "<ul><li>Import/export : les pièces d'armure se mettent à jour</li><li>Import/export : les réglages sont inclus</li><li>Infobulle de la barre d'exercices retirée (bloquait le clic)</li><li>Indice sous la barre d'exercices disparaît après 10 clics</li><li>Formules trop larges : plus d'icône, cadre pleine largeur</li><li>Zoom (pincement/double-tap) désactivé</li><li>Appui sur l'oiseau : affiche sa phrase à sa place</li><li>Infobulles réduites à une seule (le dragon)</li></ul>" },
  { v: 121, date: "11/08/2026", desc: "<ul><li>Débordement horizontal corrigé sur plusieurs pages</li><li>Bulle de l'oiseau redessinée avec phrase taquine</li><li>Lune redessinée en croissant réaliste</li><li>Densité du dragon recalée (lundi-mercredi)</li><li>Police : plus de saut visuel au chargement</li><li>Nom façon jeu vidéo sur chaque pièce d'équipement</li><li>Infobulles sur 8 zones de la scène de combat</li><li>2 renvois entre cours de maths et code</li><li>Pièce d'or tournante sur le pull-to-refresh</li></ul>" },
  { v: 120, date: "11/08/2026", desc: "<ul><li>Barrière de campagne pleine largeur, centrée</li><li>Icône personnalisée (l'oiseau) pour l'écran d'accueil</li><li>Spinner de rafraîchissement en mode application</li></ul>" },
  { v: 119, date: "11/08/2026", desc: "<ul><li>Grotte du dragon invisible</li><li>Dragon endormi calé sur la falaise</li><li>Lune : minimum d'éclairement ajouté</li></ul>" },
  { v: 118, date: "11/08/2026", desc: "Mesure d'audience anonyme et agrégée (GoatCounter)." },
  { v: 117, date: "11/08/2026", desc: "<ul><li>Débordement horizontal corrigé</li><li>Armure « forgée » : pièce entière à 100%</li><li>Objectif hebdomadaire adaptatif</li></ul>" },
  { v: 116, date: "11/08/2026", desc: "<ul><li>Nouvelles phrases pour l'oiseau, plus courtes et plus sobres</li><li>Sécurité ajoutée sur le calcul de la phase de la lune</li></ul>" },
  { v: 115, date: "11/08/2026", desc: "Fin contour ajouté à chaque pièce d'équipement du chevalier." },
  { v: 114, date: "11/08/2026", desc: "<ul><li>L'oiseau devient la mascotte permanente</li><li>Le dragon vit la semaine : sort de la grotte, combat samedi minuit</li><li>Dimanche : résultat affiché en pause</li><li>Deux phrases ajoutées en fin de fiche</li></ul>" },
  { v: 113, date: "11/08/2026", desc: "Deux nouvelles phrases dans la liste de fin de fiche." },
  { v: 112, date: "11/08/2026", desc: "<ul><li>Bouclier et épée passent devant (étaient invisibles)</li><li>Gardent leurs propres proportions</li><li>Légèrement pivotés pour un port naturel</li></ul>" },
  { v: 111, date: "10/08/2026", desc: "<ul><li>Casque : visière inversée à gauche, cheveux ne dépassent plus</li><li>Plastron : chemisier ne transparaît plus</li><li>Jambières : jean ne transparaît plus à l'entrejambe</li><li>Bottes : de nouveau deux bottes séparées</li></ul>" },
  { v: 110, date: "10/08/2026", desc: "<ul><li>8 pièces d'équipement redessinées, liseré doré</li><li>Couleur des pièces en gris/argent</li><li>Casque légèrement asymétrique</li></ul>" },
  { v: 109, date: "10/08/2026", desc: "Nouveau plan campagne (cottage, clôture, arbres) dans la scène de combat." },
  { v: 108, date: "10/08/2026", desc: "Lune : vrai disque plein au lieu d'un croissant fixe." },
  { v: 107, date: "10/08/2026", desc: "<ul><li>Musique de fond adaptative (8-bit), désactivée par défaut</li><li>RÉVISION CIBLÉE compte dans les séries de bonnes réponses</li></ul>" },
  { v: 106, date: "10/08/2026", desc: "<ul><li>Zoom réactivé partout (bug introduit par le blocage du glissement)</li><li>Même correctif sur alice-et-sophie, fiche-de-math-gael, exercices-l1-math</li></ul>" },
  { v: 105, date: "10/08/2026", desc: "Densité de la grotte recalée sur celle du château (technique interne)." },
  { v: 104, date: "10/08/2026", desc: "Lune : reflète la vraie phase lunaire du jour." },
  { v: 103, date: "10/08/2026", desc: "<ul><li>Système de profondeur à 4 plans pour la scène de combat</li><li>Lune ramenée en haut à droite (bug de position corrigé)</li></ul>" },
  { v: 102, date: "10/08/2026", desc: "Château et lune rapprochés des personnages, alignés entre eux." },
  { v: 101, date: "10/08/2026", desc: "« Trinôme » → « polynôme » du second degré (fiche Logique). (Merci Mgika3 !)" },
  { v: 100, date: "10/08/2026", desc: "<ul><li>Ménage technique : 3 fonctions dupliquées centralisées</li><li>Château et lune alignés sur les bords du cadre</li><li>Mascotte oiseau réduite de moitié</li></ul>" },
  { v: 99, date: "10/08/2026", desc: "Chapitres du menu triés du moins avancé au plus avancé." },
  { v: 98, date: "10/08/2026", desc: "<ul><li>Nouvelle page MA PROGRESSION (radar + transfert par phrase)</li><li>Nouvelle page RÉVISION CIBLÉE (10 pires exercices)</li><li>Blocage du dézoom étendu à 3 autres sites</li></ul>" },
  { v: 97, date: "10/08/2026", desc: "<ul><li>% de questions répondues affiché par chapitre</li><li>56 nouvelles phrases de fin de fiche</li><li>20 nouvelles phrases dans le bandeau d'accueil</li></ul>" },
  { v: 96, date: "10/08/2026", desc: "<ul><li>Bouton VALIDER par défaut pour les nouveaux visiteurs</li><li>Dézoom en dessous de l'affichage normal bloqué</li><li>Effet élastique retiré au glissement horizontal</li><li>Astuce ajoutée sous la barre de progression des fiches</li></ul>" },
  { v: 95, date: "10/08/2026", desc: "<ul><li>Formules : ne se coupent plus, glissables si trop larges</li><li>Combat de la semaine : temps restant avant reset affiché</li></ul>" },
  { v: 94, date: "10/08/2026", desc: "<ul><li>Formules trop larges : zone glissable signalée au lieu de déborder</li><li>Réglage VALIDATION DES RÉPONSES ajouté</li><li>Réglage AFFICHAGE DES FICHES (défilement continu) ajouté</li><li>Icône menu à gauche, badge de version en bas à gauche</li></ul> (Merci Charles Boyer !)" },
  { v: 93, date: "10/08/2026", desc: "Pièces d'équipement repositionnées avec précision sur le chevalier." },
  { v: 92, date: "05/08/2026", desc: "Débordement du badge d'équipement corrigé (fiches et cartes de chapitre)." },
  { v: 91, date: "05/08/2026", desc: "Lien « FICHE » ajouté au menu, vers fiche-de-math-gael." },
  { v: 90, date: "05/08/2026", desc: "Lien « EXERCICES TYPE » ajouté au menu, vers exercices-l1-math." },
  { v: 89, date: "05/08/2026", desc: "<ul><li>Fiches en pages de 5-6 questions au lieu d'un long défilement</li><li>« Mes erreurs fréquentes » se met à jour toute seule</li></ul>" },
  { v: 88, date: "05/08/2026", desc: "Falaise du château restaurée sur toute sa hauteur, grotte repositionnée." },
  { v: 87, date: "05/08/2026", desc: "Château de retour au-dessus de la scène de combat, avec grotte du dragon." },
  { v: 86, date: "05/08/2026", desc: "<ul><li>« Mes erreurs fréquentes » fonctionne par score, plus par disparition immédiate</li><li>Composition de fonctions en LaTeX (fiche Logique)</li><li>« Théorème » de changement de variable renommé « méthode » (fiche Analyse)</li></ul> (Merci Mgika3 !)" },
  { v: 85, date: "05/08/2026", desc: "<ul><li>Boutons chapitre précédent/suivant en bas de fiche</li><li>Nouvelle page MES ERREURS FRÉQUENTES</li><li>Objectif hebdomadaire abaissé à 60%</li></ul>" },
  { v: 84, date: "05/08/2026", desc: "<ul><li>Dragon de la défaite tourné face au chevalier</li><li>Sang ajouté sur l'épée du dragon vaincu (victoire)</li></ul>" },
  { v: 83, date: "05/08/2026", desc: "Dragon victorieux (scène de défaite) : sprite définitif." },
  { v: 82, date: "05/08/2026", desc: "Nettoyage technique : ~23 Ko de code mort supprimé." },
  { v: 81, date: "05/08/2026", desc: "Nouvelle page NOTATION : choix u/v ou f/g pour la dérivation. (Merci Yassin Hajji !)" },
  { v: 80, date: "05/08/2026", desc: "<ul><li>Barre de progression globale : bug d'affichage vide sur mobile corrigé</li><li>Pieds de la mascotte alignés sur ceux du chevalier</li><li>Pièces d'équipement repositionnées à la main</li><li>Bouton « diamant » renommé « cœur »</li></ul>" },
  { v: 79, date: "05/08/2026", desc: "<ul><li>Oiseau décoratif réduit de moitié, aligné sur les pieds du chevalier</li><li>Séparateurs sur la barre de progression globale</li><li>Équipement de nouveau visible sur le chevalier en couleur</li></ul>" },
  { v: 78, date: "05/08/2026", desc: "<ul><li>Barre de progression globale resserrée dans son cadre</li><li>Chevalier en couleur dans victoire/défaite</li><li>Notation d'équivalence resserrée sous le tilde</li></ul>" },
  { v: 77, date: "05/08/2026", desc: "<ul><li>Chevalier en couleur à la place de l'ancien bonhomme</li><li>Château retiré du fond, oiseau affiné</li><li>Texte du combat repositionné</li><li>Nouveau dragon pour la défaite</li><li>Progression globale en un carré par exercice</li><li>Page de démo pour le petit monstre</li></ul>" },
  { v: 76, date: "05/08/2026", desc: "Doublon d'oiseau retiré de la scène de combat." },
  { v: 75, date: "05/08/2026", desc: "Lune ajoutée dans le ciel de la scène de combat." },
  { v: 74, date: "05/08/2026", desc: "<ul><li>Nouvelle scène de combat : dragon endormi, oiseau, chevalier en couleur</li><li>Petit monstre traversant l'écran après 3 min d'inactivité</li><li>Scène de victoire : dragon vaincu sur le dos</li></ul>" },
  { v: 73, date: "05/08/2026", desc: "Barre de progression globale : style petits carrés, comme les fiches." },
  { v: 72, date: "04/08/2026", desc: "Le message affiché sur une bonne réponse passe de « CORRECT » à « BRAVO ! »." },
  { v: 71, date: "04/08/2026", desc: "<ul><li>Réinitialisation : l'équipement de la semaine disparaît bien</li><li>Moteur de rendu des formules hébergé sur le site</li></ul>" },
  { v: 70, date: "04/08/2026", desc: "Ordre des réponses QCM mélangé (la bonne était presque toujours en 1re position). (Merci Magaly !)" },
  { v: 69, date: "04/08/2026", desc: "Nouveaux dessins de mascotte : corbeau et monstre rond." },
  { v: 68, date: "04/08/2026", desc: "Score du combat hebdomadaire : une ligne, fond sombre pour la lisibilité." },
  { v: 67, date: "04/08/2026", desc: "<ul><li>Épée du bouton haut de page : 3 orientations selon le contexte (fiches / historique / accueil)</li><li>Scène chevalier/dragon/château déplacée en bas de l'accueil, sous les chapitres</li><li>Badge d'équipement des fiches remonté sous le titre</li><li>Nettoyage du menu des chapitres</li></ul>" },
  { v: 66, date: "04/08/2026", desc: "<ul><li>Réinitialisation (chapitre ou site) : suppression directe, avec 60s pour annuler via « REGRETS ? »</li><li>Épée du bouton haut de page pointe toujours à droite au repos</li></ul>" },
  { v: 65, date: "04/08/2026", desc: "Historique des versions : épée du bouton pointe vers la droite (retour)." },
  { v: 64, date: "04/08/2026", desc: "Graal du bouton haut de page invisible au survol (souris) : corrigé." },
  { v: 63, date: "04/08/2026", desc: "Bruitages synthétisés ajoutés au Graal du bouton haut de page." },
  { v: 62, date: "04/08/2026", desc: "<ul><li>Pantalon d'algèbre élargi (était invisible, identique au chevalier sans armure)</li><li>Bouton « haut de page » : Graal seulement au 3ᵉ appui, disparaît progressivement</li><li>Lien « RETOUR » redondant supprimé des fiches/historique</li></ul>" },
  { v: 61, date: "04/08/2026", desc: "Bouton « haut de page » : épée devient un Graal en haut de l'accueil." },
  { v: 60, date: "04/08/2026", desc: "<ul><li>Badge d'équipement miniature en bas de chaque fiche, rempli selon la progression de la semaine</li><li>L'oiseau/dragon regarde vers le chevalier</li><li>Scène de victoire : épée plantée dans le dragon plutôt que dans la main du chevalier</li><li>Bouton « haut de page » : bug d'appuis rapides corrigé</li></ul>" },
  { v: 59, date: "04/08/2026", desc: "<ul><li>Pièces d'or et crânes séparés : pièces à droite, crânes à gauche</li><li>Badge miniature d'équipement sur chaque carte de chapitre</li></ul>" },
  { v: 58, date: "04/08/2026", desc: "Illustration de défaite ajoutée pour le combat hebdomadaire." },
  { v: 57, date: "04/08/2026", desc: "Combat de la semaine : pièces d'or et crânes en pixel art, plus des nombres." },
  { v: 56, date: "04/08/2026", desc: "<ul><li>Dragon/oiseau à gauche, chevalier à droite</li><li>Silhouette de base du chevalier toujours visible</li><li>Pile de crânes compactée en ×N au-delà de 5</li></ul>" },
  { v: 55, date: "04/08/2026", desc: "<ul><li>JAVA complété : 40 → 52 QCM (exceptions, AWT)</li><li>Note/20 affichée dans une bulle au clic, plus en permanence</li><li>Flash grisé au relâchement de la bulle corrigé</li><li>Bouton « haut de page » devient raccourci accueil en haut de page</li></ul>" },
  { v: 54, date: "04/08/2026", desc: "<ul><li>Accolade sous la barre de progression globale affinée et réalignée</li><li>Note/20 déplacée sous l'accolade, ouvre l'explication au clic</li><li>Combat de la semaine déplacé sous le château/chevalier</li><li>Boutons fixes ne restent plus bloqués en blanc sur mobile</li></ul>" },
  { v: 53, date: "04/08/2026", desc: "<ul><li>Note théorique/20 raccourcie avec accolade pixel art cliquable (explication complète)</li><li>Badge, boutons et cartes alignés au pixel près</li><li>Épée du bouton « haut de page » affinée</li><li>Icône invisible au survol → corrigée ; boutons fixes stabilisés au défilement</li></ul>" },
  { v: 52, date: "04/08/2026", desc: "<ul><li>Bouton retour en haut de page (épée pixel art, bas droite)</li><li>Badge version + titre + bouton menu alignés sur une ligne</li><li>Œil de l'oiseau : un seul pixel au lieu d'un bloc de deux</li></ul>" },
  { v: 51, date: "04/08/2026", desc: "<ul><li>Badge de version qui chevauchait le bouton RETOUR → corrigé</li><li>Formule de LOGIQUE (quantificateurs) non rendue en KaTeX → corrigée</li><li>Pile de crânes farmable par resets répétés sans progrès → corrigée</li></ul>" },
  { v: 50, date: "03/08/2026", desc: "80% des exercices avant le reset = illustration de victoire : chevalier en armure, épée plantée sur le dragon vaincu." },
  { v: 49, date: "03/08/2026", desc: "Décor château + vallée en pixel art derrière la scène chevalier/dragon." },
  { v: 48, date: "03/08/2026", desc: "Chevalier hebdomadaire : chaque chapitre complété cette semaine ajoute une pièce d'équipement (bottes → épée)." },
  { v: 47, date: "03/08/2026", desc: "Combat hebdomadaire chevalier/dragon : couche à part, reset chaque lundi, victoire si 80% des exercices refaits dans la semaine." },
  { v: 46, date: "03/08/2026", desc: "JAVA refondu à partir du vrai cours : 27 → 40 QCM, 6 → 10 sections." },
  { v: 45, date: "03/08/2026", desc: "<ul><li>Mascotte oiseau/dragon qui grandit selon les jours d'inactivité</li><li>Pile de crânes + note théorique/20</li><li>Retrait de la salle au trésor et des gemmes</li></ul>" },
  { v: 44, date: "03/08/2026", desc: "Retire le système « chapitre pas encore sorti » : les 8 chapitres sont tous disponibles." },
  { v: 43, date: "03/08/2026", desc: "<ul><li>Moteur des fiches unifié en un seul fichier partagé</li><li>Barre sous le titre = grille de carrés cliquables, un par exercice</li><li>4 formules de PROBABILITÉS corrigées (KaTeX)</li><li>Nettoyage du code mort</li></ul>" },
  { v: 42, date: "03/08/2026", desc: "Supprime le sous-titre sous le titre de l'accueil." },
  { v: 41, date: "03/08/2026", desc: "Titre de l'accueil : « SYNTHÈSE » → « L1 MATHS »." },
  { v: 40, date: "03/08/2026", desc: "Symboles mal rendus (≤, ≥, ⊆…) corrigés : formules en police KaTeX, texte autour en police pixel." },
  { v: 39, date: "03/08/2026", desc: "<ul><li>Pixel manquant du grand crâne corrigé</li><li>Dates ajoutées à cet historique</li><li>Références aux enseignants retirées du code et des contenus</li></ul>" },
  { v: 38, date: "03/08/2026", desc: "« FIN DE FICHE » devient une question ouverte encourageante, tirée au hasard." },
  { v: 37, date: "03/08/2026", desc: "Numéro de version = lien vers cet historique." },
  { v: 36, date: "03/08/2026", desc: "Sections listes / boucle while / fonctions de PYTHON alignées sur le vrai cours." },
  { v: 35, date: "03/08/2026", desc: "Corrige le haut du grand crâne du menu (dôme connecté, plus de trou)." },
  { v: 34, date: "03/08/2026", desc: "Diamant tournant en haut à droite → cœur pixel-art qui bat." },
  { v: 33, date: "03/08/2026", desc: "Tête de mort du bouton reset alignée sur le modèle de référence." },
  { v: 32, date: "03/08/2026", desc: "Bandeau du bas : change à la navigation (plus par minuterie), ne garde que les blagues." },
  { v: 31, date: "03/08/2026", desc: "Blagues du bandeau du bas : 13 → 100+, tirage aléatoire sans répétition." },
  { v: 30, date: "03/08/2026", desc: "Cartes de chapitre : barre + score sur une ligne, arrêt toujours sur un carré entier." },
  { v: 29, date: "03/08/2026", desc: "Compteur de la barre globale aligné à droite, sur la ligne de la barre." },
  { v: 28, date: "03/08/2026", desc: "Supprime le badge « X exos » et le statut DISPONIBLE / À VENIR des cartes de chapitre." },
  { v: 27, date: "03/08/2026", desc: "Ajoute le compteur X/Y sur la barre de progression globale." },
  { v: 26, date: "03/08/2026", desc: "PYTHON terminé (22 → 43 QCM), JAVA ajouté (27 QCM) : les 8 chapitres sont tous disponibles." },
  { v: 25, date: "03/08/2026", desc: "Séparateur sous le titre de l'accueil → barre de progression globale." },
  { v: 24, date: "03/08/2026", desc: "LOGIQUE reconstruite : 10 → 34 QCM sur 6 sous-chapitres." },
  { v: 23, date: "03/08/2026", desc: "Ajoute les fiches PROBABILITÉS (23 QCM) et STATISTIQUES (17 QCM)." },
  { v: 22, date: "03/08/2026", desc: "Ajoute la fiche PYTHON (1re partie : variables, Matplotlib, conditions, boucle for)." },
  { v: 21, date: "03/08/2026", desc: "Le point central des boutons radio passe de blanc à noir." },
  { v: 20, date: "03/08/2026", desc: "Tête de mort repositionnée : au-dessus du texte dans le menu, en dessous sur les boutons de chapitre." },
  { v: 19, date: "03/08/2026", desc: "<ul><li>Badge de version ancré en haut</li><li>Score en vert quand un chapitre est terminé</li><li>Tête de mort en pixel art</li></ul>", note: "Pas de v18 distincte : correctif mineur embarqué avec la v19, sans changement visible." },
  { v: 17, date: "03/08/2026", desc: "Ajuste le texte, la couleur et la position des boutons de réinitialisation." },
  { v: 16, date: "03/08/2026", desc: "Explications sur les réponses incorrectes + boutons de reset par chapitre." },
  { v: 15, date: "03/08/2026", desc: "Blagues absurdes dans le bandeau du bas + police LaTeX pixelisée pour les formules." },
  { v: 14, date: "03/08/2026", desc: "Construit la fiche ANALYSE (Analyse 2)." },
  { v: 13, date: "03/08/2026", desc: "Complète la fiche CALCULUS : factorisation, primitives, systèmes d'équations." },
  { v: 12, date: "03/08/2026", desc: "Construit la fiche CALCULUS (pratique du calcul mathématique)." },
  { v: 11, date: "03/08/2026", desc: "Bug de cache navigateur corrigé + numéro de version affiché sur le site." },
  { v: 10, date: "03/08/2026", desc: "Menu coulissant des chapitres, cours détaillé, page d'accueil épurée." },
  { v: 9,  date: "03/08/2026", desc: "Construit la fiche ALGÈBRE : chapitre nombres complexes." },
  { v: 8,  date: "03/08/2026", desc: "<ul><li>Salle du trésor ajoutée</li><li>QCM passés à 3 réponses</li><li>Bug d'affichage des gemmes corrigé</li><li>Java/Python préparés</li></ul>" },
  { v: 7,  date: "02/08/2026", desc: "Remplace l'icône radar du menu par un cristal rubis animé en rotation 3D." },
  { v: 6,  date: "02/08/2026", desc: "Polices par rôle : Micro 5 (titres), Silkscreen (sous-titres), Jersey 10 (texte)." },
  { v: 5,  date: "02/08/2026", desc: "Réponse choisie = QCM validé direct." },
  { v: 4,  date: "02/08/2026", desc: "Choix de l'icône animée du menu (radar) et de la police pixel Micro 5." },
  { v: 3,  date: "02/08/2026", desc: "Refonte noir et blanc ; exercices en QCM avec rendu LaTeX." },
  { v: 2,  date: "02/08/2026", desc: "Premier lancement du site de révision L1 Maths, esthétique terminal pixelisé." },
  { v: 1,  date: "02/08/2026", desc: "Amorce du dépôt du site." },
];

function renderChangelog(){
  const container = document.getElementById('changelogContainer');
  if(!container) return;

  container.innerHTML = VERSIONS.map(entry => {
    const noteHTML = entry.note ? `<div class="changelog__note">${entry.note}</div>` : '';
    return `
      <div class="changelog__entry">
        <div class="changelog__head">
          <span class="changelog__v">v${entry.v}</span>
          <span class="changelog__date">${entry.date}</span>
        </div>
        <div class="changelog__desc">${entry.desc}</div>
        ${noteHTML}
      </div>
    `;
  }).join('');
}

document.addEventListener('DOMContentLoaded', renderChangelog);
